defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.offline.train_idql_diffusion_agent.TrainIDQLDiffusionAgent

name: ${env_name}_idql_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-offline/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
base_policy_path: /home/long/dppo/log/robomimic-pretrain/lift_pre_diffusion_mlp_ta4_td20/2025-12-10_10-00-11_42/checkpoint/state_3000.pt
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
offline_expert_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}/offline_expert.npz
offline_failure_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}/offline_failure.npz
offline_augmented_dataset_path: ${oc.env:DPPO_DATA_DIR}/robomimic/${env_name}/offline_augmented.npz

seed: 42
device: cuda:0
env_name: lift
obs_dim: 19
action_dim: 7
denoising_steps: 20
cond_steps: 1
horizon_steps: 4
act_steps: 4

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-${env_name}-offline
  run: ${now:%H-%M-%S}_${name}

offline_expert_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceQLearningDataset
  dataset_path: ${offline_expert_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}

offline_failure_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceQLearningDataset
  dataset_path: ${offline_failure_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}

offline_augmented_dataset:
  # _target_: agent.dataset.sequence.BC_4_Offline_Dataset
  # dataset_path: ${offline_augmented_dataset_path}
  # device: ${device}

train:
  n_epochs: 301
  n_critic_warmup_itr: 5
  gamma: 0.999
  actor_lr: 1e-4
  actor_weight_decay: 0
  actor_lr_scheduler:
    first_cycle_steps: 500
    warmup_steps: 10
    min_lr: 1e-5
  critic_lr: 1e-3
  critic_weight_decay: 0
  critic_lr_scheduler:
    first_cycle_steps: 500
    warmup_steps: 10
    min_lr: 1e-4
  save_model_freq: 50
  log_freq: 1
  critic_tau: 0.001  # rate of target q network update
  batch_size: 512

model:
  _target_: model.diffusion.diffusion_idql.IDQLDiffusion
  # Sampling HPs
  min_sampling_denoising_std: 0.1
  denoised_clip_value: 1.0
  network_path: ${base_policy_path}
  actor:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 16
    mlp_dims: [512, 512, 512]
    residual_style: True
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  critic_q:
    _target_: model.common.critic.CriticObsAct
    action_dim: ${action_dim}
    action_steps: ${act_steps}
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  critic_v:
    _target_: model.common.critic.CriticObs
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    mlp_dims: [256, 256, 256]
    activation_type: Mish
    residual_style: True
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}